# Generated by Django 2.2.12 on 2021-01-23 20:57

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_post', '0003_auto_20210123_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=9.823619603180518, null=True, verbose_name='How well do you think you did in the task? (1 = Very Badly, 10 = Very Well)'),
        ),
    ]
