# Generated by Django 2.2.12 on 2021-01-25 23:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_post', '0021_auto_20210125_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=5.980824375032935, null=True, verbose_name='How well do you think you did in the task? (0 = Very Badly, 10 = Very Well)'),
        ),
    ]
