# Generated by Django 2.2.12 on 2021-01-26 04:08

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_post', '0025_auto_20210125_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=2.4222460527295397, null=True, verbose_name='How well do you think you did in the task?'),
        ),
    ]
