# Generated by Django 2.2.12 on 2021-01-26 06:30

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_slider', '0005_auto_20210125_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=4.663279708648455, null=True, verbose_name="How well do you think you'll do in the task?"),
        ),
    ]
