# Generated by Django 2.2.12 on 2021-01-26 17:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_slider', '0010_auto_20210125_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=0.39124175185677457, null=True, verbose_name="How well do you think you'll do in the task?"),
        ),
    ]
