# Generated by Django 2.2.12 on 2021-01-26 17:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_slider', '0011_auto_20210126_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=3.2256355062386644, null=True, verbose_name="How well do you think you'll do in the task?"),
        ),
    ]
