# Generated by Django 2.2.12 on 2021-01-30 17:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_slider', '0014_auto_20210127_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=9.697442262539067, null=True, verbose_name="How well do you think you'll do in the task?"),
        ),
    ]
