# Generated by Django 2.2.12 on 2021-02-02 18:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_info_treatment', '0009_auto_20210202_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='probability',
            field=otree.db.models.FloatField(default=92.37405852560414, null=True, verbose_name='What is the probability that you ranked top 10%?'),
        ),
    ]
