# Generated by Django 2.2.12 on 2021-02-03 17:08

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_info_treatment', '0016_auto_20210202_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='probability',
            field=otree.db.models.FloatField(default=47.23100476987289, null=True, verbose_name='What is the probability that you ranked top 10%?'),
        ),
    ]
