# Generated by Django 2.2.12 on 2021-02-03 17:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence_info_treatment', '0017_auto_20210203_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='probability',
            field=otree.db.models.FloatField(default=69.49886038000255, null=True, verbose_name='What is the probability that you ranked top 10%?'),
        ),
    ]
