# Generated by Django 2.2.12 on 2021-01-24 00:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_pre', '0019_auto_20210123_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=5.80173535808905, null=True, verbose_name="How well do you think you'll do in the task? (0 = Very Badly, 10 = Very Well)"),
        ),
    ]
