# Generated by Django 2.2.12 on 2021-01-25 23:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_pre', '0033_auto_20210123_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=3.8095011928108313, null=True, verbose_name="How well do you think you'll do in the task? (0 = Very Badly, 10 = Very Well)"),
        ),
    ]
