# Generated by Django 2.2.12 on 2021-01-30 18:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ans_correct',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='answer',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='self_rating1',
            field=otree.db.models.IntegerField(default=6.97008941569928, null=True, verbose_name="How well do you think you'll do in the task?"),
        ),
        migrations.AddField(
            model_name='player',
            name='self_rating2',
            field=otree.db.models.IntegerField(default=7.990665922597261, null=True, verbose_name='How well do you think you did in the task?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='probability',
            field=otree.db.models.IntegerField(default=32.948119312707036, null=True, verbose_name='What is the probability that you outperformed 90% of the participants in the previous task?'),
        ),
    ]
