# Generated by Django 2.2.12 on 2021-01-23 18:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='centered_sliders',
        ),
        migrations.RemoveField(
            model_name='player',
            name='num_sliders',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slider_max',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slider_min',
        ),
        migrations.AddField(
            model_name='player',
            name='c_later',
            field=otree.db.models.IntegerField(default=6.81879765274473, null=True, verbose_name='How do you wish to allocate your endowment?'),
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
