# Generated by Django 2.2.12 on 2021-01-23 18:57

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0009_auto_20210123_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='c_later',
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=otree.db.models.IntegerField(default=6.923332803409027, null=True, verbose_name="How well do you think you'll do?"),
        ),
    ]
