# Generated by Django 2.2.12 on 2021-01-23 18:57

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0010_auto_20210123_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=otree.db.models.IntegerField(default=0.939956838976429, null=True, verbose_name="How well do you think you'll do?"),
        ),
    ]
