# Generated by Django 2.2.12 on 2021-02-02 00:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_prob', '0100_auto_20210201_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='probability',
            field=otree.db.models.FloatField(default=59.557745042120956, null=True, verbose_name='What is the probability that you outperformed 90% of the participants?'),
        ),
    ]
