# Generated by Django 2.2.12 on 2021-02-02 01:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_prob', '0105_auto_20210201_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='probability',
            field=otree.db.models.FloatField(default=66.90734426594989, null=True, verbose_name='What is the probability that you ranked top 10%?'),
        ),
    ]
