# Generated by Django 2.2.12 on 2021-02-02 01:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_prob', '0115_auto_20210201_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='probability',
            field=otree.db.models.FloatField(default=50.37619458491673, null=True, verbose_name='What is the probability that you ranked top 10%?'),
        ),
    ]
