# Generated by Django 2.2.12 on 2021-02-02 06:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0002_auto_20210201_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Q10',
            field=otree.db.models.FloatField(default=28.394048251845184, null=True, verbose_name='Q10?'),
        ),
    ]
