# Generated by Django 2.2.12 on 2021-02-02 06:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0003_player_q10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Q1',
            field=otree.db.models.IntegerField(blank=True, null=True, verbose_name='Q1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q10',
            field=otree.db.models.FloatField(blank=True, default=9.797681424972204, null=True, verbose_name='Q10'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q2',
            field=otree.db.models.FloatField(blank=True, null=True, verbose_name='Q2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q3',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Q3'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q4',
            field=otree.db.models.CurrencyField(blank=True, null=True, verbose_name='Q4'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q5',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='Q5'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q6',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='Q6'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q7',
            field=otree.db.models.BooleanField(blank=True, choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Q7'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q8',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'A'], [2, 'B'], [3, 'C']], null=True, verbose_name='Q8'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q9',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D']], null=True, verbose_name='Q9'),
        ),
    ]
