# Generated by Django 2.2.12 on 2021-02-02 06:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0004_auto_20210201_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Q10',
            field=otree.db.models.FloatField(blank=True, default=79.20350772673697, null=True, verbose_name='Q10'),
        ),
    ]
