# Generated by Django 2.2.12 on 2021-02-02 06:35

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0005_auto_20210201_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Q10',
            field=otree.db.models.FloatField(blank=True, default=7.437515177335651, null=True, verbose_name='Q10'),
        ),
    ]
