# Generated by Django 2.2.12 on 2021-02-02 17:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0006_auto_20210201_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Q10',
            field=otree.db.models.FloatField(blank=True, default=68.19984009353969, null=True, verbose_name='Q10'),
        ),
    ]
