# Generated by Django 2.2.12 on 2021-02-02 18:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0008_auto_20210202_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Q4',
            field=otree.db.models.FloatField(blank=True, default=57.777535217356004, null=True, verbose_name='Q4'),
        ),
    ]
