# Generated by Django 2.2.12 on 2021-02-22 21:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0012_auto_20210202_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Q1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Q2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Q3',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=otree.db.models.IntegerField(blank=True, null=True, verbose_name='What is your age?'),
        ),
        migrations.AddField(
            model_name='player',
            name='children',
            field=otree.db.models.IntegerField(blank=True, null=True, verbose_name='How many children do you have?'),
        ),
        migrations.AddField(
            model_name='player',
            name='consent',
            field=otree.db.models.BooleanField(blank=True, choices=[[True, 'Yes'], [False, 'No']], null=True, verbose_name='Given all the information above, do you agree to participate in our labor market study?'),
        ),
        migrations.AddField(
            model_name='player',
            name='education',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Some high school or less'], [2, 'High school diploma or equivalent'], [3, 'Some college'], [4, 'College diploma'], [5, 'Some graduate school'], [6, 'Graduate degree']], null=True, verbose_name='What is the highest level of education you have completed?'),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Email address:'),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Male'], [2, 'Female'], [3, 'Other, please speficify']], null=True, verbose_name='What is your gender?'),
        ),
        migrations.AddField(
            model_name='player',
            name='household',
            field=otree.db.models.IntegerField(blank=True, null=True, verbose_name='Including yourself, how many people live in your household?'),
        ),
        migrations.AddField(
            model_name='player',
            name='location',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D']], null=True, verbose_name='Where do you live?'),
        ),
        migrations.AddField(
            model_name='player',
            name='marital',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Single (never married)'], [2, 'Married'], [3, 'Separated'], [4, 'Divorced'], [5, 'Widowed'], [6, 'Domestic partnership (living together but not married)']], null=True, verbose_name='What is your marital status?'),
        ),
        migrations.AddField(
            model_name='player',
            name='religion',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Jewish'], [2, 'Muslim'], [3, 'Christian'], [4, 'Other, please speficify']], null=True, verbose_name='How do you identify?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q4',
            field=otree.db.models.FloatField(blank=True, default=81.45594862502958, null=True, verbose_name='Q4'),
        ),
    ]
