# Generated by Django 2.2.12 on 2021-02-22 23:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0013_auto_20210222_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Q4',
            field=otree.db.models.FloatField(blank=True, default=50.86596850672992, null=True, verbose_name='Q4'),
        ),
    ]
