# Generated by Django 2.2.12 on 2021-02-23 00:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0017_auto_20210222_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender_other',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='If you picked "Other" , please speficify:'),
        ),
        migrations.AddField(
            model_name='player',
            name='religion_other',
            field=otree.db.models.LongStringField(blank=True, null=True, verbose_name='If you picked "Other" , please speficify:'),
        ),
        migrations.AlterField(
            model_name='player',
            name='Q4',
            field=otree.db.models.FloatField(blank=True, default=48.851031218941976, null=True, verbose_name='Q4'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Male'], [2, 'Female'], [3, 'Other']], null=True, verbose_name='What is your gender?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='religion',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Jewish'], [2, 'Muslim'], [3, 'Christian'], [4, 'Other']], null=True, verbose_name='How do you identify?'),
        ),
    ]
