# Generated by Django 2.2.12 on 2021-02-23 00:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0018_auto_20210222_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Q4',
            field=otree.db.models.FloatField(blank=True, default=31.296937841308004, null=True, verbose_name='Q4'),
        ),
    ]
