# Generated by Django 2.2.12 on 2021-02-23 00:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0019_auto_20210222_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Q4',
            field=otree.db.models.FloatField(blank=True, default=4.999138401041325, null=True, verbose_name='Q4'),
        ),
    ]
