# Generated by Django 2.2.12 on 2021-02-23 00:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('unincentivized_Q', '0020_auto_20210222_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Q10',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Q4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Q5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Q6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Q7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Q8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Q9',
        ),
        migrations.AlterField(
            model_name='player',
            name='gender_other',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='If you picked "Other" , please speficify:'),
        ),
        migrations.AlterField(
            model_name='player',
            name='religion_other',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='If you picked "Other" , please speficify:'),
        ),
    ]
