# Generated by Django 2.2.12 on 2021-01-26 06:18

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=3.8539667132923663, null=True, verbose_name='How well do you think you did in the task?'),
        ),
    ]
