# Generated by Django 2.2.12 on 2021-01-27 17:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_slider', '0013_auto_20210126_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=0.7009493516370124, null=True, verbose_name='How well do you think you did in the task?'),
        ),
    ]
