# Generated by Django 2.2.12 on 2021-01-27 15:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_slider', '0014_auto_20210127_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='self_rating',
            field=otree.db.models.IntegerField(default=7.493908385698713, null=True, verbose_name='How well do you think you did in the task?'),
        ),
    ]
